winui/Applying-patches/Applying-patches.md
winui/AutoComplete/Getting-Started.md
winui/AutoComplete/Grouping.md
winui/AutoComplete/Keyboard-Support.md
winui/AutoComplete/Overview.md
winui/AutoComplete/Searching-Filtering.md
winui/AutoComplete/Selection.md
winui/AutoComplete/UI-Customization.md
winui/accessibility.md
winui/localization.md
winui/overview.md
winui/samples.md
winui/themes.md

DOC-4094-WinUI-UG-set1

---

winui/Ribbon/Backstage.md

</ribbon:backstageview/> -> <ribbon:backstageview/>

WinUI-100 Fixed error in code snippet

---

winui/DataGrid/Row-Drag-and-Drop.md
winui/TreeGrid/Row-Drag-and-Drop.md

WINUI - 2387-Need to modify the RowDragandDrop content PART-1

WINUI-2387 - Need to modify the RowDragandDrop content PART-1.

---

winui/DataGrid/Row-Drag-and-Drop.md
winui/TreeGrid/Row-Drag-and-Drop.md

Hi Team,
I have updated the DataGrid and TreeGrid API reference links for RowDragAndDrop feature in our UG. Could you please review it and let me know your concerns.?
Regards,
Sathiyathanam

WINUI-2410 - Need to update the API reference link RowDragAndDrop feature in our UG for both DataGrid and TreeGrid

---

winui/Ribbon/Getting-Started.md

Worked on Weblink Validator Broken links, merge these changes.
Regards,
Gowthaman

SEO-2245_Site_Audit_Issues

---

winui/DataGrid/Editing.md
winui/DataGrid/Selection.md
winui/TreeGrid/Editing.md

Task Link -https://syncfusion.atlassian.net/browse/WINUI-2662
I have fixed the side topic issue in Editing, Selection in DataGrid and Editing in Treegrid.

WINUI-2662 : Ensure and modify the DataGrid and TreeGrid UG document side topics

---

winui/Shadow/Customization.md
winui/Shadow/Getting-Started.md

Changed the UG content of shadow control in WinUI for content team review changes.

WinUI-2539 : Content team review changes added for shadow control UG in WinUI

---

winui/DataGrid/Columns.md
winui/DataGrid/Row-Drag-and-Drop.md
winui/DataGrid/Rows.md
winui/TreeGrid/Columns.md
winui/TreeGrid/Row-Drag-and-Drop.md

Hi @susmitha-sundar ,
I have modified the API names in  RowDragDrop and Freezepanes samples. 
I have updated the API name AllowDraggingsRows into AllowRowDragDrop in RowDragDrop sample. 
I also updated the FrozenFooterColumnCount and FrozenFooterColumnCount into FrozenFooterColumnsCount and FrozenFooterColumnsCount respectively in Freezepanes sample. 
https://syncfusion.atlassian.net/browse/WINUI-2744 
Could you please review it and let me know your concerns.
Regards,
Swathi D.

WINUI-2744 - Modify API names for RowDragDrop and Freezepanes

---

winui/Scheduler/Appointment-Editing.md
winui/Scheduler/Events.md

XAMARIN-43498-newly added feature is updated in WinUi Scheduler is reviewed by @Chrispineagunja

XAMARIN-43498-newly added feature is updated in WinUi Scheduler

---

winui/System-Requirements.md

IN-18172-UG-Documentation-dev

---

winui/DataGrid/Rows.md

Modify API names for RowDragDrop and Freezepanes.

WINUI-2744 - Modify API names for RowDragDrop and Freezepanes - PART 2

---

winui/DataGrid/Columns.md
winui/DataGrid/Row-Drag-and-Drop.md
winui/DataGrid/Rows.md
winui/TreeGrid/Columns.md
winui/TreeGrid/Row-Drag-and-Drop.md

Hi @susmitha-sundar ,
I have updated the API links in RowDragDrop and Freezepanes samples.
I have updated the AllowRowDragDrop API link in RowDragDrop sample.
I also updated the FrozenColumnsCount and FrozenFooterColumnsCount API links in Freezepanes sample.
https://syncfusion.atlassian.net/browse/WINUI-2744
Could you please review it and let me know your concerns.
Regards,
Swathi D.

WINUI-2768 - Add API links for freeze panes and row drag and drop APIs

---

winui/Linear-Gauge/pointers.md
winui/Linear-Gauge/shape-pointer.md
winui/Radial-Gauge/content-pointer.md
winui/Radial-Gauge/getting-started.md
winui/Radial-Gauge/pointers.md
winui/Radial-Gauge/shape-pointer.md

To add API reference links for WinUI Gauges' properties in UG content.

WINUI-2776 : Include API reference links for WinUI Gauges UG changes

---

winui/Installation/offline-installer/how-to-download.md
winui/Installation/web-installer/how-to-download.md
winui/Licensing/how-to-generate.md
winui/Licensing/licensing-errors.md
winui/Licensing/licensing-faq/how-to-upgrade-from-trial-version-after-purchasing-a-license.md
winui/Licensing/licensing-faq/registering-syncfusion-account-for-nuget-org-user.md
winui/Licensing/overview.md

IN-18200-UG-Link-Changes-winui-hotfix

---

winui/Linear-Gauge/shape-pointer.md
winui/Radial-Gauge/content-pointer.md

To resolve the issues upon including the API links for WinUI Gauges' properties.

WINUI-2776 : H2 changes in WinUI RadialGauge content pointer UG.

---

winui-toc.html
winui/Common/compact-sizing.md

WINUI-2758-Changed the file paths in Common folder in winui-toc.html file.

WINUI-2758-changed file path in winui-toc file

---

winui/overview.md

I have added the Shadow control in WinUI UG controls overview.

WinUI-2819 : Added the shadow control in WinUI UG controls overview.

---

winui/Common/compact-sizing.md

WINUI-2758-updated the changes in the content.

WINUI-2758-updated content changes

---

winui/DataGrid/FilterRow.md

Prepare and include the UG document for DateFilter support for Filter Row

WINUI-2979 Prepare and include the UG document for DateFilter support for Filter Row

---

winui/Ribbon/Getting-Started.md

Hi @jeganraj-m ,
Changed the API name from "SizeMode" to "AllowedSizeModes" in the UG document.
Regards,
Umamaheswari N.

WINUI-3023-Changed "SizeMode" API to "AllowedSizeModes"

---

winui/DataGrid/Export-To-Excel.md

I have removed the extra spaces in the excel exporting UG.

WINUI-2978 : Update the excel exporting UG.

---

winui/BusyIndicator/AnimationType.md
winui/BusyIndicator/Overview.md
winui/Rating/Overview.md
winui/Rating/Precision.md
winui/Rating/ToolTip.md

Changed the content in the rating and busy indicator control.

WinUI-2902 : Changed the content in the rating and busyindicator control.

---

winui/Rating/Customization.md

Changed the header text size and added the emoji template selector code in customization in Rating control UG.

WinUI-2902 : Changed the headertext size and added the emoji templateselector code in UG

---

winui/Linear-Gauge/shape-pointer.md
winui/Radial-Gauge/shape-pointer.md

Need to add API reference links to the WinUI linear and radial gauges UG content.

WINUI-3082 : Added API reference links to shape pointer md files

---

winui/Cartesian-Charts/Axis/Axislabels.md
winui/Cartesian-Charts/Axis/Gridlines.md
winui/Cartesian-Charts/Axis/Ticklines.md
winui/Cartesian-Charts/Axis/Types.md
winui/Cartesian-Charts/Getting-Started.md
winui/Cartesian-Charts/Legend.md
winui/Cartesian-Charts/Selection.md
winui/Cartesian-Charts/Tooltip.md
winui/Circular-Charts/Getting-Started.md
winui/Circular-Charts/Selection.md
winui/Circular-Charts/Tooltip.md
winui/Funnel-Chart/Getting-Started.md
winui/Funnel-Chart/Selection.md
winui/Funnel-Chart/Tooltip.md
winui/Polar-Chart/Axis-Labels.md
winui/Pyramid-Chart/Getting-Started.md
winui/Pyramid-Chart/Selection.md
winui/Pyramid-Chart/Tooltip.md

Add new API links for the new API changes in the WinUI chart controls.
[If there is an external design, link to its project documentation area.
If there is an internal discussion on the forum, provide the link.](https://syncfusion.sharepoint.com/sites/XamarinChart/_layouts/15/Doc.aspx?sourcedoc={4d149321-98e7-41ca-a4c9-9ba91b394ac3}&action=edit&wd=target%28WinUI%20Chart.one%7C6e982125-140d-45fb-b696-9c12636c7f7c%2FWinUI%20Chart%20API%20Breaking%20Changes%20Review%7Cbae4d30c-59b1-4bd7-a948-6a6b07427f40%2F%29&wdorigin=NavigationUrl)
Added new API links for the new API changes in the WinUI chart controls.
NA
NA
NA

WINUI-3072 Add new API links for the WinUI chart documents

---

winui/BusyIndicator/AnimationType.md
winui/BusyIndicator/Content.md
winui/BusyIndicator/Customization.md
winui/BusyIndicator/Getting-Started.md
winui/BusyIndicator/Overview.md
winui/Rating/Customization.md
winui/Rating/Getting-Started.md
winui/Rating/Overview.md
winui/Rating/Precision.md
winui/Rating/ToolTip.md

Changed the content review changes in the busy indicator and rating control in UG documentation.

WinUI-3091 : Committed the content review changes in the busyindicator and rating control

---

winui/Cartesian-Charts/Selection.md
winui/Circular-Charts/Selection.md
winui/Funnel-Chart/Selection.md
winui/Pyramid-Chart/Selection.md

Update API link for the chart selection changed event

WINUI-3090  Update API link for the chart selection changed event

---

winui/Busy-Indicator/AnimationType.md
winui/Busy-Indicator/Content.md
winui/Busy-Indicator/Customization.md
winui/Busy-Indicator/Getting-Started.md
winui/Busy-Indicator/Overview.md
winui/Rating/Customization.md
winui/Rating/Getting-Started.md
winui/Rating/Overview.md
winui/Rating/Precision.md
winui/Rating/ToolTip.md

Added the API Properties link in rating and busy indicator control.

WinUI-3091 : Added the API properties link in the rating and busyindicator control.

---

winui/DataGrid/Export-To-Excel.md

Since the API links have been generated for the property in Excel Exporting. So updated their links.

WINUI-3099 : Update the API links for excel exporting UG in WinUI DataGrid,

---

winui/Busy-Indicator/AnimationType.md
winui/Rating/ToolTip.md

- Added the default value in animation type MD file in the BusyIndicator control.
- Added the tooltip format ms link in the tooltip MD file in the Rating control.

WinUI-2902 : Added the default value in animation type and link in the tooltip format.

---

winui/Ribbon/Getting-Started.md

-Modified the indent issue in the UG documentation

Test-34450-Corrected the indent issues in WinUI UG documentation

---

winui/overview.md

I have added the Rating and BusyIndicator control in WinUI UG controls overview.

WinUI-2902 : Added the Rating and BusyIndicator control in WinUI UG controls overview

---

winui/overview.md

I have added the Rating and BusyIndicator control in WinUI UG controls overview.

WinUI-2902 : Added the Rating and BusyIndicator control in WinUI UG controls overview.

---

winui/Funnel-Chart/Legend.md
winui/Funnel-Chart/Selection.md
winui/Polar-Chart/Appearance.md
winui/Polar-Chart/Axis-Labels.md
winui/Polar-Chart/DataLabel.md
winui/Polar-Chart/Getting-Started.md
winui/Polar-Chart/Legend.md
winui/Polar-Chart/Polar-Area.md
winui/Polar-Chart/Polar-Line.md
winui/Pyramid-Chart/Legend.md
winui/Pyramid-Chart/Selection.md

Added proper redirect link for pyramid and funnel chart UG

WINUI-3190-Added proper redirect link for the pyramid and funnel chart UG.

---

winui/overview.md

Updated the control name in the editors.

WinUI-3229-Updated the control name in the editors.

---

winui/overview.md

Updated the control name in the editors.
Already merged the changes in the development and now updated in hotfix.

WinUI-3229 : Updated the control name in editors hotfix.

---

winui/Masked-TextBox/Culture.md
winui/Masked-TextBox/Customization.md
winui/Masked-TextBox/Formatting-Value.md
winui/Masked-TextBox/Getting-Started.md
winui/Masked-TextBox/Mask-Types.md
winui/Masked-TextBox/Overview.md

Updated the API reference links for the SfMaskedTextBox control.

WinUI-3229 : Updated API reference links for SfMaskedTextBox control.

---

winui/Masked-TextBox/Culture.md
winui/Masked-TextBox/Customization.md
winui/Masked-TextBox/Formatting-Value.md
winui/Masked-TextBox/Getting-Started.md
winui/Masked-TextBox/Mask-Types.md
winui/Masked-TextBox/Overview.md
winui/overview.md

Updated the control name Masked TextBox into a single word in UG document.
Updated the name in the editors control names overview file also.

WinUI-3229 : Updated the Masked TextBox into a single word in UG document.

---

winui/Masked-TextBox/Culture.md
winui/Masked-TextBox/Customization.md
winui/Masked-TextBox/Formatting-Value.md
winui/Masked-TextBox/Getting-Started.md
winui/Masked-TextBox/Mask-Types.md
winui/Masked-TextBox/Overview.md
winui/overview.md

Updated the control name Masked TextBox into a single word in UG document.
Updated the name in the editors control names overview file also.

WinUI-3229 : Updated Masked TextBox into single word in hotfix.

---

winui-toc.html

- Added reference for Ribbon Compact Sizing UG document in winui html file.

WINUI-3237-Added reference for Ribbon Compact Sizing

---

winui/Ribbon/Getting-Started.md
winui/Shadow/Getting-Started.md

Hi @Aishwarya-Ganesan ,
Have changed Winui redirect links, please review.
Regards,
Yvone.

SEO-3297 Winui Redirect

---

winui/Date-Picker/Getting-Started.md
winui/Pyramid-Chart/Getting-Started.md
winui/Radial-Gauge/getting-started.md
winui/RangeSlider/getting-started.md
winui/Rating/Getting-Started.md
winui/Scheduler/Getting-Started.md
winui/SegmentedControl/Getting-Started.md
winui/Slider/getting-started.md
winui/Time-Picker/Getting-Started.md
winui/TreeGrid/Getting-Started.md
winui/TreeView/Getting-Started.md

Hi, I have worked on the links with redirects.
Regards,
Beryl.

SEO-3283-Links-With-Redirects-Winui

---

winui/Avatar-view/content-types.md
winui/Avatar-view/customization.md
winui/Avatar-view/getting-started.md
winui/Avatar-view/overview.md
winui/Avatar-view/visual-styles.md

Review changes given by the content team

WINUI-3339-Content-Review-Changes

---

winui/overview.md

Addition of AvatarView link in overview under Miscellaneous.

WINUI-3339-AvatarView link addition in overview

---

winui/Avatar-view/content-types.md
winui/Avatar-view/customization.md
winui/Avatar-view/getting-started.md
winui/Avatar-view/overview.md
winui/Avatar-view/visual-styles.md
winui/Busy-Indicator/Overview.md
winui/Masked-TextBox/Overview.md
winui/Rating/Overview.md
winui/Shadow/Overview.md

Addition of API reference links.

WINUI-3402-API reference additions

---

winui/Cartesian-Charts/FastCharts/Fast-Scatter.md
winui/Cartesian-Charts/Tooltip.md
winui/Cartesian-Charts/Trackball.md
winui/Circular-Charts/Tooltip.md
winui/Funnel-Chart/Tooltip.md
winui/Pyramid-Chart/Tooltip.md

I added checked and added the proper API reference links for the new breaking changes in the WINUI charts UG.

WINUI-3389-Add API reference links for breaking changes in WINUI charts UG.

---

winui/System-Requirements.md

Hi @SubashiniMahendran 
I have updated the Windows app SDK version in the system requirements section of the WinUI help link document.
Regards
Yuvaraj M

WinUI-829976- Updated system requirements

---

winui/AutoComplete/Getting-Started.md
winui/Badge/Badge-Customization.md
winui/Badge/Getting-Started.md
winui/Barcode/Getting-Started.md
winui/Calendar/Getting-Started.md

Worked on weblink page with redirect links for WinUI. Kindly review.
Regards,
Sharly A.

SEO-172146 - WinUI Controls Weblinks

---

winui/Cartesian-Charts/Axis/AutoScrollingDelta.md

Updated API links for WinUI Cartesian chart

WinUI-837285-Update-API-links-for-AutoScrollingDelta-UG-Content

---

winui/Cartesian-Charts/Axis/AutoScrollingDelta.md

Updated API links for WinUI Cartesian chart

WinUI-837285 Update API links for AutoScrolling Delta feature 

---

winui/Linear-Gauge/animation.md

Have worked on changing Page with Redirect links.
Regards,
Yvone.

SEO-175190 WinUI Page with Redirect

---

winui/Cartesian-Charts/DataLabels.md
winui/Cartesian-Charts/Getting-Started.md
winui/Circular-Charts/DataLabels.md
winui/Circular-Charts/Explode.md
winui/Circular-Charts/Getting-Started.md
winui/Polar-Chart/DataLabel.md
winui/Polar-Chart/Getting-Started.md

I have added the API link for WinUI chart properties.

Added API links for WinUI Chart properties.

---

winui-toc.html

Hi all,
- With this PR, we have added DocIO & Presentation controls in WINUI platform UG.
Regards,
Dharanitharan A

ES-846833-Add DocIO & Presentation controls in WINUI platform UG-hotfix

---

winui/Ribbon/Ribbon-QAT.md

Addressed all the appearance in UG.

Addressed the apperance issue

---

winui/Ribbon/Ribbon-QAT.md

Resolved the conflict in merging the hotfix to development branch.

ES-836428 Resolved the conflict

---

winui/System-Requirements.md

Have changed Page with Redirect links.
Regards,
Yvone.

SEO-175659 WinUI Page with Redirect

---

winui-toc.html

Hi All,
Modify the TOC file for DocIo and Presentation Product.
Task Link: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/851567
Regards
venkatesh

ES-851567 Modify TOC File

---

winui/System-Requirements.md

Hi @SubashiniMahendran 
I have updated .Net 8.0 in WINUI System Requirements. Please review and merge the changes
Regards
Yuvaraj M

856149-Updated .Net 8.0 in WINUI System-Requirements

---

winui/Color-Palette/Getting-Started.md
winui/Color-Picker/Getting-Started.md

Hello,
I have worked on links with redirects.
Regards,
Beryl.

SEO-176113-UG-Links-With-Redirects-WINUI

---

winui/Masked-TextBox/Culture.md
winui/Masked-TextBox/Customization.md
winui/Masked-TextBox/Error-Indication.md
winui/Masked-TextBox/Events.md
winui/Masked-TextBox/Formatting-Value.md
winui/Masked-TextBox/Getting-Started.md
winui/Masked-TextBox/How-To.md
winui/Masked-TextBox/Mask-Types.md
winui/Masked-TextBox/Overview.md

Update the API reference links for error indication feature in Masked Textbox and also update the control name MaskedTextBox as "Masked TextBox"  for all UG pages of masked textbox.

WPF-862845-Update the API reference links for error indication feature in Masked Textbox Hotfix

---

winui/Masked-TextBox/Culture.md
winui/Masked-TextBox/Customization.md
winui/Masked-TextBox/Error-Indication.md
winui/Masked-TextBox/Events.md
winui/Masked-TextBox/Formatting-Value.md
winui/Masked-TextBox/Getting-Started.md
winui/Masked-TextBox/How-To.md
winui/Masked-TextBox/Mask-Types.md
winui/Masked-TextBox/Overview.md

Update the API reference links for error indication feature in Masked Textbox and also update the control name MaskedTextBox as "Masked TextBox"  for all UG pages of masked textbox.

WPF-862845-Update the API reference links for error indication feature in Masked Textbox Development

---

winui/Busy-Indicator/Getting-Started.md

Hi @MallikaRK,
Worked on WinUI page with redirect.
Regards,
Sharly A.

SEO-179237-WinUI-Redirection-Links-

---

winui/Masked-TextBox/Error-Indication.md
winui/Ribbon/Ribbon-QAT.md

Hello
I have worked on links with redirects.
Regards,
Beryl.

SEO-178945-UG-On-Page-Improvement-WinUI

---

winui/Masked-TextBox/Getting-Started.md

I have changed redirection links, please review.
Regards,
Scholar.

SEO-179789- WinUI Redirection links

---

winui/DropDown-Color-Picker/Getting-Started.md
winui/Shadow/Getting-Started.md

Hi @MallikaRK ,
Kindly review the redirect link changes.
Thanks.
Regards,
Edith.

SEO-179251-WinUI-Page-with-redirects

---

winui/Calendar-DateRange-Picker/Localization-And-Formatting.md
winui/Cartesian-Charts/Getting-Started.md
winui/Circular-Charts/Getting-Started.md
winui/Pyramid-Chart/Getting-Started.md
winui/TreeView/Load-on-demand.md

Hi @MallikaRK ,
Kindly review the changes.
Regards,
Edith.

SEO-180844-winui-issue-fix

---

winui/DataGrid/Autosize-Columns.md
winui/DataGrid/Master-Details-View.md

Resolved the correction in DataGrid MasterDetailsView Document.

Resolved the correction in MasterDetailsView

---

winui/Scheduler/Appointments.md
winui/Scheduler/Day-Week-Views.md
winui/Scheduler/Month-View.md
winui/Scheduler/Timeline-Views.md

I have updated the API links for the Scheduler tooltip.

WinUI 890011 - Updated the API links for Scheduler tooltip content

---

winui/DataGrid/Getting-Started.md

Title | Description
-- | --
Task Category | Page with Redirect|
Content Task Link/Mail Screenshot | NA|
Hotfix | https://github.com/syncfusion-content/winui-docs/pull/893|
Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187645/|
Work link | https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B5956DB12-BF41-423F-9337-A60CF7314B63%7D&file=Yvone.xlsx&action=default&mobileredirect=true |
Changes Made | Reason for change | Reason for not identifying earlier
-- | -- | --
Page with Redirect | To avoid redirection 301 or 302 links, providing direct links. |  
Regards,
Yvone.

SEO-187645 WinUI DataGrid Page with Redirect

---

winui-toc.html

Task - https://dev.azure.com/Syncfusion-Infrastructure/Install/_workitems/edit/187726/

187726 - Syncfusion License Validation Page Location Updated - Live

---

winui/DataGrid/Autosize-Columns.md

Included API reference for the  feature in the user guide documentation

ES-904219 - Included the API reference Link.

---

winui-toc.html
winui/AI-AssistView/Getting-started.md
winui/AI-AssistView/Overview.md
winui/AI-AssistView/Suggestions.md
winui/AI-AssistView/Themes.md
winui/AI-AssistView/Typing-indicator.md
winui/AI-AssistView/open-ai.md

**Description**
Review changes updated in the AI AssistView UG documentation.

WinUI-920210 : Review changes updated in the AI AssistView UG documentation.

---

winui-toc.html
winui/AI-AssistView/Getting-started.md
winui/AI-AssistView/Overview.md
winui/AI-AssistView/Suggestions.md
winui/AI-AssistView/Themes.md
winui/AI-AssistView/Typing-indicator.md
winui/AI-AssistView/open-ai.md

**Description**
Review changes updated in the AI AssistView UG documentation

WinUI-920210 : Review changes updated in the AI AssistView UG documentation.[Development]

---

winui/AI-AssistView/Getting-started.md
winui/AI-AssistView/open-ai.md

**Description**
Updated the demo sample link in GettingStarted and OpenAI.

WinUI-906900 : Updated the demo sample link in GettingStarted and OpenAI.

---

winui/System-Requirements.md

Hi @SubashiniMahendran
I have updated .Net 9.0 in WINUI System Requirements. Please review and merge the changes
Regards
Yuvaraj M

Update net 9.0 changes

---

winui/System-Requirements.md

Hi @SubashiniMahendran,
I have removed the preview vs in system requirements for WinUI Platform. Review and merge the changes.
Regards
Yuvaraj M

removed the preview vs in system requirements

---

winui/Scheduler/Month-View.md

I have added the UG content for below feature:
- Number of Visible Weeks support - WinUI Scheduler.

925962-Update the UG documentation for scheduler control newly implemented features.

---

winui-toc.html
winui/Kanban/cards.md

Added kanban cards UG content.

925953 - [WinUI Kanban] Added kanban cards content

---

winui-toc.html
winui/Kanban/cards.md

Added UG content  WinUI Kanban cards.

925953 - Added UG content  WinUI Kanban cards 

---

winui/Kanban/cards.md

Resolved WinUI Kanban Cards content alignment issue.

925887-WinUI Kanban cards content alignment issue resolved

---

winui-toc.html
winui/Kanban/cards.md
winui/Kanban/columns.md

WinUI Kanban column and cards content added

925953 - [Hotfix] WinUI Kanban column and cards content added

---

winui-toc.html
winui/Kanban/swimlane.md

Added swimlane content for WinUI Kanban control

925953 - [hotfix] Added swimlane content for WinUI Kanban control

---

winui/overview.md

Added WinUI Kanban control in overview

925953 - [hotfix] Added WinUI Kanban control in overview

---

winui-toc.html
winui/Kanban/events.md

WinUI Kanban events changes added.

925953 - [hotfix] WinUI Kanban events changes added

---

winui/Kanban/getting-started.md

WinUI Kanban Examples link added.

925953-[hotfix] WinUI Kanban Examples link added

---

winui/Kanban/cards.md
winui/Kanban/columns.md
winui/Kanban/getting-started.md

Added API links for Kanban control.

925887- Added API links for Kanban control-hotfix

---

winui/Scheduler/Month-View.md

Updated missed changes in Scheduler Xaml controls.

929457 - Updated missed changes in Scheduler Xaml controls

---

winui/overview.md

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>
<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>
<div style='direction:ltr;border-width:100%'>
<div style='direction:ltr;margin-top:0in;margin-left:0in;width:7.7416in'>
<div style='direction:ltr;margin-top:0in;margin-left:0in;width:7.7416in'>
<div style='direction:ltr'>
Title | Description
-- | --
Task Link | IN -   198113 Updating Banner Content in Documentation
Feature description | To   update the content in the overview pages
Analysis and design | N/A
Output screenshots | N/A
Areas affected and ensured | Changes …

Update Banner Dev

---

winui/overview.md

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>
<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>
<div style='direction:ltr;border-width:100%'>
<div style='direction:ltr;margin-top:0in;margin-left:0in;width:7.7416in'>
<div style='direction:ltr;margin-top:0in;margin-left:0in;width:7.7416in'>
<div style='direction:ltr'>
Title | Description
-- | --
Task Link | IN -   198113 Updating Banner Content in Documentation
Feature description | To   update the content in the overview pages
Analysis and design | N/A
Output screenshots | N/A
Areas affected and ensured | Changes …

Update WinUI Hotfix

---

winui/Kanban/cards.md
winui/Kanban/columns.md
winui/Kanban/events.md
winui/Kanban/getting-started.md
winui/Kanban/overview.md
winui/Kanban/swimlane.md

**Description:**
Update Trademark symbol in the WinUI Kanban control documents.

[hotfix] 944741- Update the Trademark symbol in WinUI Kanban documents.

---

winui/Kanban/events.md

Winui Kanban example code changes updated.

937986 - Winui Kanban example code changes updated

---

winui/Kanban/workflows.md

WinUI Kanban example code tab title changes  updated.

937986 - WinUI Kanban example code tab title changes 

---

winui/DataGrid/Row-Drag-and-Drop.md

Hi @MallikaRK 
|Title|Description|
|--|--|
|Task Category| Site Audit
|Content Task Link/Mail Screenshot| NA|
|UX task| NA|
|Hotfix|https://github.com/syncfusion-content/winui-docs/pull/1063
|Ticket/Task link|https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/200110/
|Excel/SharePoint link| NA| https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B20474523-6AF0-4D8C-9BF4-5AF6C037651B%7D&file=Duplicate%20Title.xlsx&action=default&mobileredirect=true
|Changes made|Reason for changes|
|--|--|
|Updated valid link| To solve redirected link|
Regards,
Mercy A.

SEO-Site-Audit-WinUI-Datagrid-incorrect-URL

---

winui/AI-AssistView/Response-Toolbar.md

Prepare UG document content for response toolbar item support in SfAIAssistView control for WinUI.

964318-Prepare UG document content for response toolbar item support in SfAIAssistView control for WinUI

---

winui/AI-AssistView/Getting-started.md

Remove the unwanted lines in the document.

Removed the unwanted lines in the document.

---

winui/Kanban/getting-started.md

WinUI Kanban UG review corrections addressed.
https://github.com/syncfusion-content/winui-docs/pull/1144

977013-[Dev] WinUI Kanban UG review corrections addressed
